//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORT_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_ticket
    {
        public int ID_ticet { get; set; }
        public string Photo_3x4 { get; set; }
        public string Photo_signature { get; set; }
        public string Photo_of_passport { get; set; }
        public string Document_number { get; set; }
        public string Notification { get; set; }
        public Nullable<bool> Document_selection { get; set; }
        public Nullable<int> Graduent { get; set; }
    
        public virtual Graduant Graduant { get; set; }
    }
}
