//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORT_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Fired_Employee = new HashSet<Fired_Employee>();
            this.Receipt = new HashSet<Receipt>();
        }
    
        public int ID_Employee { get; set; }
        [Required(ErrorMessage="Пожалуйста введите фамилию")]
        public string Surname { get; set; }
        [Required(ErrorMessage = "Пожалуйста введите имя")]
        public string First_name { get; set; }
        public string Third_Name { get; set; }
        [Required(ErrorMessage = "Пожалуйста укажите дату рождения")]
        public System.DateTime Birth_date { get; set; }
        [Required(ErrorMessage = "Пожалуйста укажите пол")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Пожалуйста введите номер телефона")]
        public string Phone_number { get; set; }
        [Required(ErrorMessage = "Пожалуйста укажите ИНН")]
        public string INN_passport { get; set; }
        [Required(ErrorMessage = "Пожалуйста укажите адрес")]
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Date_of_appointment { get; set; }
        public Nullable<bool> Fired { get; set; }
        public Nullable<byte> Position { get; set; }
        public Nullable<byte> Access_level { get; set; }
        public Nullable<short> District { get; set; }
        public Nullable<short> School { get; set; }
        public Nullable<int> Authotization { get; set; }
    
        public virtual Access_level Access_level1 { get; set; }
        public virtual Authorization Authorization { get; set; }
        public virtual District_town_ District_town_ { get; set; }
        public virtual Position Position1 { get; set; }
        public virtual School School1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fired_Employee> Fired_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipt { get; set; }
    }
}
