//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORT_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fired_Employee
    {
        public short id_fired { get; set; }
        public Nullable<System.DateTime> Date_leavingFierd { get; set; }
        public Nullable<System.DateTime> Date_appointmentFired { get; set; }
        public Nullable<int> ID_Employee { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
