//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORT_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Limit_of_time
    {
        public short ID_Time { get; set; }
        public System.DateTime Date_of_limit { get; set; }
        public System.DateTime Limit_start { get; set; }
        public Nullable<System.DateTime> Limit_end { get; set; }
    }
}
