//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORT_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int ID_Raceipt { get; set; }
        public string Receipt_num { get; set; }
        public decimal Receipt_sum { get; set; }
        public System.DateTime Payment_Date { get; set; }
        public string Bank_branch_num { get; set; }
        public Nullable<short> School { get; set; }
        public Nullable<int> Head_of_teacher { get; set; }
        public Nullable<int> Graduent { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Graduant Graduant { get; set; }
        public virtual School School1 { get; set; }
    }
}
