//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORT_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class SignaturesTable
    {
        public int ID { get; set; }
        public int FK_Graduant { get; set; }
        public string Photo3x4 { get; set; }
        public string PhotoSignature { get; set; }
    
        public HttpPostedFileBase ImageFile { get; set; }
        public HttpPostedFileBase ImageFileSign { get; set; }
        public virtual Graduant Graduant { get; set; }
    }
}
